### ISSUE TITLE
screen won't centralize and has uneven borders

### ISSUE THREAD

**Issue by benjis8888** [kodi-game/game.libretro.flycast#8]
San Francisco rush 2049 is one and there is quite a few it happens on, and has a big empty space at the bottom and the inbuilt screen repositioning won't work either

![San Francisco Rush 2049-ECHELON-230223-111632](https://user-images.githubusercontent.com/126162906/220894715-f6873752-f8c2-4564-a977-bf05f1f1c604.png)
![San Francisco Rush 2049-ECHELON-230223-111646](https://user-images.githubusercontent.com/126162906/220894728-47c1c73b-d2ba-40a4-90bf-062cf34c9dfd.png)

**Comment by lrusak** [comment]
flycast doesn't even work in Kodi currently. Are you looking for the upstream repo? https://github.com/flyinghead/flycast
